name: release

on: [push]

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: macOS-latest
    timeout-minutes: 60

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Build app
        run: |
          # Remove old CommandLineTools to fix ARM builds
          sudo rm -rf /Library/Developer/CommandLineTools

          xcodebuild -project DynamicUniversalApp.xcodeproj -configuration Release

      - name: Store build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/Release
          if-no-files-found: error
